spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?characterEncoding=utf-8&userSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  freemarker:
    template-loader-path: classpath:/templates
    cache: false
    charset: utf-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"
server:
  port: 9001
mybatis:
  mapper-locations: classpath:mappers/*
  configuration:
    map-underscore-to-camel-case: true
wx:
  appId: wx3e6b9f1c5a7ff034
  mchId: 1614433647
  mchKey: Aa111111111122222222223333333333
  notifyUrl: http://cwatae.natappfree.cc/pay/notify
  returnUrl: http://127.0.0.1
ali:
  appId: 2021003175608816
  aliPayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjmzn6tiONu2/RGBHmMr0XKYKl86x8Xr0wigpG/e6j6NbPkzuWdL2gw2xgDiaRmpGB+oMWeA9ABE4yXriwsFBH/8V0JqLxCpQaDYQxg1p+q6HaslsdjMZ63pmygyuz0saUGCeMG4V+f5jhtHh7bFhWMXZ/Iz6olpPXx5xOtFePs8N2vJ+7bH7mtErls8P11CuOgyNq3kFCwXBAVKBF4YFbVxSTgYiQsLjBtgRXkQjdyMeo9n2URr+NxStzZY4kZXhGf1mZZrlvA1xdNj8iwH+D9tmsGAYqE6zmEud754ImRc5Likc/HZCP696L2wSWRDZuipmrb8WHJcJ+AI/fFctkwIDAQAB
  privateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCqo3HxnrHJjNE8MCIpmsh8ypTPUZaHuVg3ySpsqr7A9DPeDR9J5EY+WFZjlT9AklgEa2YE+eRzV+dB55rp4IO/aPUkzpJNTwui7olz/v/6vfBn0zzwoQ4LiPGLHBB1tkt1N7QCIz1rniZukx2Bt9Rz0+nq02P8FhG7OhTFVoWN+3LGqiFoIsbm9VRW+TaDvyO9dP+NDitD2ZVtthmgB8IjoqR5RMcW4ozIKCWHJjkVY4JmEz90tGFG4o5i6YX/fDq53cnLuDNQv4C8+Zg8plQtT7sG/7saoeGhSr8ceRBH6DHavQXiXkICdwKdYRJ0eHy0sfiVqfrIQzyyMmQqU/yTAgMBAAECggEBAJEzSac3ycNe30DfGILcohOGcsBDhdryPX4i4MXdOTqJ0oT2F5TR+W/dzY0pl8xDe0Avf31mgx4fQ7rR8QFoudMr5cYvPVEpnRZE8pPQ/lOIQsSmfGmqMoBgRGGCPQNdXrJc9wEGqaIkzkEzUF1sZw002wymWqNMyEPQNZKCgF0CnRQWQ+zparvLkXkmoeEsVF44XcdndgISxDaYxqkjY8yW3VhmmMNIA2C/KlU6jgkzJl/B1QC/mrh2zS+A+4dTKni8V0UaAeOaQ1H0a7Ki8QJr2HbkBmisVz780n+z7L0e/M8QwnaNAJu/4G7Idusj25V14LLONFAXdc9lG6wBxQECgYEA9cLxsT0M6ewWBP+Bzj/VZ/6C28x1kNl4rRVAnhg7ArrsnEFt8KJRHC77sBC2kt/XLcl0CFdCB+QqCjuYBhMVt/2oxD9LrGnX9jeCZRDw+coW5BTdvp0BmMZuUjQRt3QTZ+q0gshANeOo4ppxgFg1/0erRGkbagzF9Qknnte5hBMCgYEAsb9PknMWFc4eK+BkaVqoeysb7oyVlddGrjt89sN7JGQ9znRL9txGFn8dhoYZeq7TEWN23ZsyYx4DDeLrMMD3XHSJOvURfy/kpkBxkaOSx2IoXo0e2qtKDBthbwo+Pcn+tbh/v6iqN+kYARF6pZJK3BhKxqlcK4TgfH0hI9+NtYECgYEA7Ldx/4rTZnmdGAFXcWbw0jNGrhm43+VopCaFUAH8zPtpLnSjRZXC1Ie4q/TdNolehN624dXSZzFxANw36Rn24Hr2VNi2tgJZHvKGqXxw79ikxdoHYDNwt0viNVGsAu1OR9i9N/9UQdPf9yxVyQ6uLA5HPCSVYEefYQ8JV6loKnsCgYA2q03REF6hlETJX/niQYUCZQ7xPwIfFRhjLF7SEuvEFKTB5BkdM0DHWI9/Oa2Kg0zd00bTABHuVGPCGKIX27H5GMrAfHHGObfMvpNvpOzXMESUWDk+LmLW+HDuUyszm/YgdD+udjTsf1/nrDWZyTYHHd2Z3qs/o13cTCwuOWr/gQKBgFYdCNIfxrR0pBTvfC2Fx8RY3m4S6K33zw89utw+exikXYKSlr980uNm4bMM/ASdVnPbHabJYjgMMdW1B4aVA2jGBXODsyDM1yTuZNAjSJbD3BYSugvyJxLUSh/HwnQS8ofGD8Dn6BIF9AiliDwOvn59Ix8yAtuAfIfzRZRY3txg
  notifyUrl: http://cwatae.natappfree.cc/pay/notify
  returnUrl: http://127.0.0.1